### PR TITLE
Minor HTML page edit

### LINKED ISSUE #4: No Link to Source
It would be useful if the demo page had a link to this [GitHub repo](https://github.com/chadselph/smssplit).

### PR DESCRIPTION
**Pull request by Deantwo**
Added a basic link to the GitHub page
Added a label to the input box.

Fixes: #4

I have not tested this, and I am not that good with HTML. Thoughts?

### CODE REVIEW

**Comment by chadselph** [comment]
Seems fine. Some pages have like a nice badge/logo but I couldn't find out if there's like an easy/standard way to do that

**Comment by Deantwo** [comment]
Or just add it to a header or footer on the page.

Only example I got is https://staxmanade.com/ExceptionMessageBeautifier/.

**Comment by chadselph** [comment]
Trying out this guy https://tholman.com/github-corners/

**Comment by Deantwo** [comment]
Looks nice. I am closing this pull request then.
Commit for reference: https://github.com/chadselph/smssplit/commit/bf167a4fdb3e6b54aa2917803bef087dc3140be0

**Pull request closed without merging**
